FROM elasticsearch:7.10.1

RUN elasticsearch-plugin install -b https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.10.1/elasticsearch-analysis-ik-7.10.1.zip
RUN elasticsearch-plugin install analysis-smartcn
